// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ttuQIwv1xZcjqmBUXYI-ZoJBbmMAIm4',
    appId: '1:353160601799:web:791552d7441e1947dd9ee2',
    messagingSenderId: '353160601799',
    projectId: 'project-flutter-93897',
    authDomain: 'project-flutter-93897.firebaseapp.com',
    storageBucket: 'project-flutter-93897.appspot.com',
    measurementId: 'G-6PGNCXL5ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHYRH19oIhhrOeT5JTTQDD-CexVh2Oi4',
    appId: '1:353160601799:android:d787959a42783865dd9ee2',
    messagingSenderId: '353160601799',
    projectId: 'project-flutter-93897',
    storageBucket: 'project-flutter-93897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjmep2yA5NAYH9R4MahJMtgULnQVhfgw',
    appId: '1:353160601799:ios:90d3f441f236b4e3dd9ee2',
    messagingSenderId: '353160601799',
    projectId: 'project-flutter-93897',
    storageBucket: 'project-flutter-93897.appspot.com',
    iosClientId: '353160601799-aaimbj63prjvqbpo1ajgvvrga208bks5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
